-- Functions & procedures
\i /home/schema/functions/autoset_timestamp_cols.sql

-- Tables
\i /home/schema/users.sql
\i /home/schema/positions.sql
\i /home/schema/other_certs.sql
\i /home/schema/night_crews.sql
\i /home/schema/fuel_log.sql
\i /home/schema/events.sql
\i /home/schema/equipment.sql
\i /home/schema/ems_certs.sql
\i /home/schema/drivers_licenses.sql
\i /home/schema/default_schedule.sql
\i /home/schema/credentials.sql
\i /home/schema/audit_log.sql
\i /home/schema/users_positions.sql
\i /home/schema/users_other_certs.sql
\i /home/schema/users_ems_certs.sql
\i /home/schema/users_credentials.sql
\i /home/schema/radio_locations.sql
\i /home/schema/radio_distribution.sql
\i /home/schema/promo_requests.sql
\i /home/schema/individual_checklist_items.sql
\i /home/schema/event_logs.sql
\i /home/schema/eval_items.sql
\i /home/schema/checklist_items.sql
\i /home/schema/attendees.sql
\i /home/schema/users_eval_items.sql
\i /home/schema/users_checklist_items.sql
\i /home/schema/promo_request_votes.sql
