\i schema/users.sql
\i schema/positions.sql
\i schema/other_certs.sql
\i schema/night_crews.sql
\i schema/fuel_log.sql
\i schema/events.sql
\i schema/equipment.sql
\i schema/ems_certs.sql
\i schema/drivers_licenses.sql
\i schema/default_schedule.sql
\i schema/credentials.sql
\i schema/audit_log.sql
\i schema/users_positions.sql
\i schema/users_other_certs.sql
\i schema/users_ems_certs.sql
\i schema/users_credentials.sql
\i schema/radio_locations.sql
\i schema/radio_distribution.sql
\i schema/promo_requests.sql
\i schema/individual_checklist_items.sql
\i schema/event_logs.sql
\i schema/eval_items.sql
\i schema/checklist_items.sql
\i schema/attendees.sql
\i schema/users_eval_items.sql
\i schema/users_checklist_items.sql
\i schema/promo_request_votes.sql